### PR TITLE
[ISSUE CONFIRMED] Right Seperator for CSB based on CurrentCulture

### PR DESCRIPTION
**Pull request by lancepioch**
The comma is the default separator for CSV (comma separated value) files. Also there's no pokemon that have commas (present or future) in their name.

### CODE REVIEW

**Comment by Spegeli** [comment]
This will destroy the list:

http://i.epvpimg.com/qk8oe.png

**Comment by Flumadiddle** [comment]
This is what it looks like for me.
Looks

**Comment by Flumadiddle** [comment]
This is due to list separation localization setting in Windows.

**Comment by Spegeli** [comment]
Yeah this is the same issue as with the GPXPathing.
German must be commas and US must be use dots.

**Comment by Spegeli** [comment]
Can you pls grab the latest Version and let me know if its fixed for your.
On German it makes the right output.

**Comment by Spegeli** [comment]
I changed now the whole logic and added some more infos.
Please grab the latest Version. 
please let me know if it works now correct for you.

**Comment by Flumadiddle** [comment]
Yes, it is now working.

**Pull request closed without merging**
