### PR TITLE
Added Total Pokes in bag to title

### PR DESCRIPTION
**Pull request by C-Sto**
Caching might make this info incorrect - but should be fine as a rough data point

### CODE REVIEW

**Comment by Spegeli** [comment]
Seems not fetching the correct datas.
I own 1754 Pokemon, the bot say 166.

**Comment by C-Sto** [comment]
Ah, have discovered the source of error, your pokemon bag in the application counts the eggs as well as the pokemon - will write a fix

**Comment by Spegeli** [comment]
But then it should count more and not less?!

**Comment by C-Sto** [comment]
No, I mean in the mobile application the number includes the eggs, in the bot/client it does not

**Comment by Spegeli** [comment]
Your right, will add the Pokemon later ;-)

**Comment by Spegeli** [comment]
Added with the next version and will be extended with a "Pokemon Bag space" when i found out how ^^

**Pull request closed without merging**
