### PR TITLE
Needed steps to run on mono / linux

### PR DESCRIPTION
**Pull request by 0xFEEDC0DE64**
Please always use Path.Combine or Path.DirectorySeparatorChar when building file paths.
It created folders called "\Config" and "\Logs" on my linux machine!

### CODE REVIEW

**Comment by Spegeli** [comment]
for what is the new GeoCoordinate.cs file?

**Comment by 0xFEEDC0DE64** [comment]
There is no System.Device in mono / linux

**Comment by Spegeli** [comment]
Replcae using System.Device.Location with your new file will not work:

http://i.epvpimg.com/8YqVf.png

**Comment by 0xFEEDC0DE64** [comment]
Why can I compile it?
You are calling some other library? Maybe I can "fake" the same namespace.
image

**Comment by Spegeli** [comment]
Please grab the latest release and let me know if everything is working.

**Comment by MythHack** [comment]
Sorry, I will not be using github, so here mentioned problems. FeroxRev has updated the new api(https://github.com/FeroxRev/Pokemon-Go-Rocket-API), I hope my tips will be helpful. If I do not help this project, I am very sorry.

**Comment by 0xFEEDC0DE64** [comment]
I will not say that it works, but you can start the application now on linux. That was all my pull request offered. Now we need to dig deeper to find out why it crashes after a minute runtime.

**Comment by kevinqkh** [comment]
Can you do evolve every n hours function?

**Comment by kevinqkh** [comment]
so you can just use luckyeggs when evolving

**Comment by 0xFEEDC0DE64** [comment]
@kevinqkh why do ask that in a pull request? please go to the chat and ask there.

**Pull request closed without merging**
